@host = localhost
@port = 8080
@sheme = http
@domain = {{sheme}}://{{host}}:{{port}}

### admin login
# @name login
GET {{domain}}/api/auth/login HTTP/1.1
Authorization: Basic ADM1 password

@jwt = {{login.response.body.access_token}}
@refreshToken = {{login.response.body.refresh_token}}

### user login
# @name login
GET {{domain}}/api/auth/login HTTP/1.1
Authorization: Basic USR1 password

@jwt = {{login.response.body.access_token}}
@refreshToken = {{login.response.body.refresh_token}}

### fail: refresh-token instead of jwt
GET {{domain}}/api/any/bar HTTP/1.1
Authorization: Bearer {{refreshToken}}
Accept: application/json

### fail: refresh-token with jwt
# @name login
GET {{domain}}/api/auth/refresh-token HTTP/1.1
Authorization: Bearer {{jwt}}

### refresh-token
# @name login
GET {{domain}}/api/auth/refresh-token HTTP/1.1
Authorization: Bearer {{refreshToken}}

@jwt = {{login.response.body.access_token}}
@refreshToken = {{login.response.body.refresh_token}}

### temp bar Admin
GET {{domain}}/api/any/boo HTTP/1.1
Authorization: Bearer {{jwt}}
Accept: application/json

### temp bar Admin, User
GET {{domain}}/api/any/bar HTTP/1.1
Authorization: Bearer {{jwt}}
Accept: application/json


### temp baz Admin, User
GET {{domain}}/api/any/baz HTTP/1.1
Authorization: Bearer {{jwt}}
Accept: application/json