server:
  port: 8080
spring:
  profiles:
    active: default
  application:
    name: jott
    version: "@project.version@"
  data:
    rest:
      base-path: /api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:25433/db}
    username: ${SPRING_DATASOURCE_USERNAME:db}
    password: ${SPRING_DATASOURCE_PASSWORD:db}
    driverClassName: org.postgresql.Driver
  docker:
    compose:
      file: src/main/resources/db/docker-compose.yml
      lifecycle: start-and-stop
      skip:
        in-tests: true
  jpa:
    properties:
      hibernate:
        jdbc.batch_size: 200
        order_inserts: true
        ddl-auto: none
        format_sql: true
        highlight_sql: true
  sql:
    init:
      platform: mysql
  mvc:
    log-request-details: true
springdoc:
  swagger-ui:
    enabled: true
    tryItOutEnabled: false
    filter: false
    syntaxHighlight.activated: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm.jdbc.bind: TRACE
      springframework:
        security: TRACE
        web: TRACE
    web: DEBUG
com.abach42.jott:
  basePath: /api
  security:
    jwt:
      # must be at least 256 bits,
      # caution: never commit key in production, consider to use env var
      token-secret: ks9lg8pubax3ctmw9aq4pz4vduxllqq4
debug: false