spring:
  profiles:
    active: default
  application:
    name: jott
    version: "@project.version@"
  data:
    rest:
      base-path: /api
  datasource:
    url: jdbc:postgresql://localhost:25433/db
    username: db
    password: db
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc.batch_size: 200
        order_inserts: true
        ddl-auto: none
        format_sql: true
        highlight_sql: true
  sql:
    init:
      platform: mysql
  mvc:
    log-request-details: true
springdoc:
  swagger-ui:
    enabled: true
    tryItOutEnabled: true
    filter: false
    syntaxHighlight.activated: true
debug: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm.jdbc.bind: TRACE
      springframework:
        security: TRACE
        web: TRACE
    web: DEBUG
com.abach42.jott:
  basePath: /api
  security:
    jwt:
      # must be at least 256 bits,
      # caution: never commit key in production, consider to use env var
      token-secret: ks9lg8pubax3ctmw9aq4pz4vduxllqq4